# Generated by Django 4.0.5 on 2022-06-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
